### ISSUE TITLE
Print STL

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-connect#6]
For our new app (and other apps) to print to the WiFi-Box we'd like to add functionality to connect.doodle3d.com so we can print stl files (or meshes in general). 
This would require for example:
- Include our Slicer.
- Create Slicer configuration pages
- Save this Slicer configuration somewhere... (On WiFi-Box, Doodle3D community or browser?) I would prever on the WiFi-Box, but this would require allowing more / custom settings) 
- Embeddable wizard to for example select a WiFi-Box and go through the slicing proces. Check how 3D Hubs does this.

**Comment by companje** [comment]
It's now possible to print to the WiFi-Box from Doodle3D Transform. 3D models are sliced by Doodle3D Transform, GCODE is uploaded to a server. connect.doodle3d.com is opened by Transform  and from a print command can be send to the WiFi-Box after which the WiFi-Box will start printing the GCODE file from the server.
